name: Integration Continue

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 17
      uses: actions/setup-node@v3
      with:
        node-version: 17

    - name: Install dependencies (frontend)
      run: npm install

    - name: Run ESLint (frontend)
      run: npm run lint

  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: backend 